In [ ]:
#!pip install tensorflow

In [1]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from scikeras.wrappers import KerasClassifier

import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv(r'C:\Users\Aditya Desai\Downloads\Neural_network\Alphabets_data.csv')
data

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [4]:
data.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [ ]:
# Handling missing values and normalize data

In [5]:
# Check for missing values
print(data.isnull().sum())

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [6]:
# Separating the features and the target variable
X = data.drop('letter', axis=1)
y = data['letter']

In [7]:
# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Model Implementation

### using tensorflow and keras to construct a basic ANN model

In [8]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [9]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

In [10]:
# Define a function to create the Keras model
def create_model(optimizer='adam', activation='relu', learning_rate=0.001):
    model = Sequential([
        Dense(64, input_shape=(X_train.shape[1],), activation=activation),
        Dense(32, activation=activation),
        Dense(len(label_encoder.classes_), activation='softmax')
    ])
    model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

In [11]:
# Create a KerasClassifier wrapper
model = KerasClassifier(build_fn=create_model, verbose=0)

In [12]:
# Train the model
model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), batch_size=32)

KerasClassifier(
	model=None
	build_fn=<function create_model at 0x000002AC0008A8C0>
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=None
	validation_batch_size=None
	verbose=0
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=1
	class_weight=None
)

In [13]:
# Predict the test set
y_pred_initial_probs = model.predict_proba(X_test)
y_pred_initial = y_pred_initial_probs.argmax(axis=1)

In [14]:
# Evaluate the model
initial_accuracy = accuracy_score(y_test, y_pred_initial)
initial_precision = precision_score(y_test, y_pred_initial, average='weighted')
initial_recall = recall_score(y_test, y_pred_initial, average='weighted')
initial_f1 = f1_score(y_test, y_pred_initial, average='weighted')

print("Initial Model Performance")
print(f"Accuracy: {initial_accuracy}")
print(f"Precision: {initial_precision}")
print(f"Recall: {initial_recall}")
print(f"F1-Score: {initial_f1}")
print(classification_report(y_test, y_pred_initial))

Initial Model Performance
Accuracy: 0.94625
Precision: 0.9473524324788033
Recall: 0.94625
F1-Score: 0.9461785923975855
              precision    recall  f1-score   support

           0       0.94      0.97      0.95       149
           1       0.92      0.97      0.94       153
           2       0.95      0.93      0.94       137
           3       0.89      0.98      0.93       156
           4       0.93      0.93      0.93       141
           5       0.96      0.94      0.95       140
           6       0.97      0.90      0.94       160
           7       0.96      0.81      0.88       144
           8       0.93      0.97      0.95       146
           9       0.96      0.91      0.93       149
          10       0.85      0.94      0.89       130
          11       0.94      0.97      0.95       155
          12       0.96      0.96      0.96       168
          13       0.93      0.91      0.92       151
          14       0.94      0.95      0.95       145
          15       0.97      0.97      0.97       173
          16       0.97      0.99      0.98       166
          17       0.89      0.93      0.91       160
          18       0.97      0.92      0.95       171
          19       0.98      0.97      0.97       163
          20       0.96      0.96      0.96       183
          21       0.99      0.95      0.97       158
          22       0.95      0.97      0.96       148
          23       0.97      0.95      0.96       154
          24       0.99      0.98      0.98       168
          25       0.93      0.96      0.94       132

    accuracy                           0.95      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.95      0.95      0.95      4000

## Hyperparameter Tuning

In [15]:
# Define the hyperparameters grid
param_grid = {
    'model__optimizer': ['adam', 'rmsprop', 'sgd'],
    #'model__learning_rate': [0.001, 0.01, 0.1],
    'model__activation': ['relu', 'sigmoid', 'tanh'],
    'batch_size': [16, 32, 64],
    'epochs': [25, 50, 100]
}

In [16]:
# Perform grid search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(X_train, y_train)

In [17]:
# Display the best parameters
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

Best: 0.9341876752561378 using {'batch_size': 32, 'epochs': 100, 'model__activation': 'relu', 'model__optimizer': 'adam'}

In [18]:
# Get the best model from GridSearchCV
best_model = grid_result.best_estimator_

In [19]:
# Predict the test set probabilities with the tuned model
y_pred_tuned_probs = best_model.predict_proba(X_test)

In [20]:
# Find the index of the maximum probability for each sample
y_pred_tuned = y_pred_tuned_probs.argmax(axis=1)

In [21]:
# Evaluate the tuned model
tuned_accuracy = accuracy_score(y_test, y_pred_tuned)
tuned_precision = precision_score(y_test, y_pred_tuned, average='weighted')
tuned_recall = recall_score(y_test, y_pred_tuned, average='weighted')
tuned_f1 = f1_score(y_test, y_pred_tuned, average='weighted')

print("Tuned Model Performance")
print(f"Accuracy: {tuned_accuracy}")
print(f"Precision: {tuned_precision}")
print(f"Recall: {tuned_recall}")
print(f"F1-Score: {tuned_f1}")
print(classification_report(y_test, y_pred_tuned))

Tuned Model Performance
Accuracy: 0.9555
Precision: 0.9559964841482447
Recall: 0.9555
F1-Score: 0.9553712621858643
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       149
           1       0.93      0.93      0.93       153
           2       0.98      0.93      0.95       137
           3       0.97      0.92      0.94       156
           4       0.93      0.99      0.96       141
           5       0.94      0.94      0.94       140
           6       0.96      0.93      0.95       160
           7       0.91      0.84      0.87       144
           8       0.98      0.92      0.95       146
           9       0.95      0.99      0.97       149
          10       0.94      0.94      0.94       130
          11       0.94      0.99      0.96       155
          12       0.93      1.00      0.97       168
          13       0.99      0.91      0.95       151
          14       0.95      0.95      0.95       145
          15       0.97      0.96      0.96       173
          16       0.95      0.98      0.97       166
          17       0.89      0.94      0.91       160
          18       0.98      0.96      0.97       171
          19       0.97      0.95      0.96       163
          20       0.97      0.96      0.96       183
          21       0.96      0.97      0.96       158
          22       0.99      0.98      0.98       148
          23       0.96      0.99      0.97       154
          24       1.00      0.98      0.99       168
          25       0.94      0.97      0.96       132

    accuracy                           0.96      4000
   macro avg       0.96      0.95      0.95      4000
weighted avg       0.96      0.96      0.96      4000

### Overall, the hyperparameter tuning process resulted in a slight improvement in model performance across all metrics. This improvement demonstrates the importance of hyperparameter optimization in achieving better model performance and generalization on unseen data.